name: 'docs'

on:
  push:
    branches: [main]
    paths:
      - 'apps/docs/**'
      - '.github/workflow/docs.yaml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./apps/docs
        run: pnpm build
      - name: Test
        working-directory: ./apps/docs
        run: pnpm test