name: 'docs'

on:
  push:
    branches: [main]
    paths:
      - 'apps/docs/**'
      - '.github/workflow/docs.yaml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.15.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Cache node_modules
        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      # Runs a single command using the runners shell
      - name: Download dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        
      - name: Build
        run: pnpm build --filter=docs
      # - name: Test
      #   working-directory: ./apps/docs
      #   run: pnpm test